<?php $block->renderFileLessToCss(); ?>

<header id="lucian_header123" class="header-container">
	<div class="top-link header-link">
		<div class="container">
			<div class="container-iner">
				<div class="row">
					<div class="col-md-6 col-xs-12">
						<?php echo $this->getChildHtml("currency"); ?>
						<?php echo $this->getChildHtml("store_language"); ?>
					</div>
					<div class="col-md-6 col-xs-12">
						<div class="top-link-dropdown">
							<?php echo $this->getChildHtml("header.links"); ?>
						</div>
						 <?php echo $this->getChildHtml("header_social"); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="header-content">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-xs-12">
					<div class="groud">
						<div class="mobile-bar-icon"><span><?php /* @escapeNotVerified */ echo __('mobile icon'); ?></span></div>
						
						<div class="logo-home">
							<?php echo $this->getChildHtml("logo"); ?>
						</div>
						<?php echo $this->getChildHtml("header_phone_home8"); ?>
						<div class="cartmobile-item">
							<?php echo $this->getChildHtml("cartmobile");?>
						</div>
					</div>
				</div>
				<div class="col-md-7 col-xs-12">
					<div class="hozmenu">
						<?php echo $block->getLayout()->createBlock('Plazathemes\Hozmegamenu\Block\Menu')->setTemplate('hozmegamenu.phtml')->toHtml();?>
					</div>					
				</div>
			</div>
		</div>
	</div>
	<div class="header-menu">
		<div class="container">
			<div class="menu-inner">
				<div class="row">
					<div class="col-md-3 col-xs-12">
						<?php echo $this->getChildHtml("verticalmegamenu_top"); ?>
					</div>
					<div class="col-md-9 col-xs-12">
						<div class="header-right">
							<?php echo $this->getChildHtml("top.search"); ?>
							<div class="login">
								<?php
								$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
								$customerSession = $objectManager->create('Magento\Customer\Model\Session');
								if($customerSession->isLoggedIn()) { //customer is loggedin or not
								?>
									<a href="<?php echo $this->getUrl('customer/account/logout'); ?>"><?php echo __('Sign Out') ?></a>
								<?php
								}else{
								?>
									<a href="<?php echo $this->getUrl('customer/account/login'); ?>"><?php echo __('Sign In') ?></a>
								<?php
								}
							?>
							</div>
							<div class="detop">
								<?php echo $this->getChildHtml("miniwishlist");?>
								<?php echo $this->getChildHtml("minicart");?>
							</div>
						</div>
					</div>
					
				</div>	
			</div>	
		</div>
	</div>
	<div class="mobile-bar-content">
	   <div class ="mobile-bar-close"><?php /* @escapeNotVerified */ echo __('Close'); ?></div>
	   <ul class = "tabs-mobile">
		<li class="item item-menu"><?php /* @escapeNotVerified */ echo __('Menu'); ?></li>
		<li class="item item-account"><?php /* @escapeNotVerified */ echo __('Account'); ?></li>
		<li class="item item-setting"><?php /* @escapeNotVerified */ echo __('Setting'); ?></li>
	   </ul>
	   <div class="tabs-content-mobile tabs-menu">
		<?php echo $this->getChildHtml("mobilemenu"); ?>
	   </div>
	   <div class="tabs-content-mobile tabs-account" style="display:none;">
		<?php echo $this->getChildHtml("header.links"); ?>
	   </div>
	   <div class="tabs-content-mobile tabs-setting" style="display:none;">
		<?php echo $this->getChildHtml("store_language_mobile"); ?>
		<?php echo $this->getChildHtml("currency_mobile"); ?>
	   </div>
	</div>
</header>
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
 $(document).ready(function(){
  <!-- show, hide mobile bar content -->
  $(".mobile-bar-icon").click(function(){
   $(".mobile-bar-content").addClass("open");
  });
  $(".mobile-bar-close").click(function(){
   $(".mobile-bar-content").removeClass("open");
  });
  
  <!-- choose tabs-->
  $(".tabs-mobile .item-menu").addClass("active");
  $(".tabs-mobile .item").click(function(){
   $(".tabs-mobile .item").removeClass("active");
   $(this).addClass("active");
  });
  $(".tabs-mobile .item-menu").click(function(){
   $(".tabs-content-mobile").css("display","none");
   $(".tabs-menu").css("display","block");
  });
  $(".tabs-mobile .item-account").click(function(){
   $(".tabs-content-mobile").css("display","none");
   $(".tabs-account").css("display","block");
  });
  $(".tabs-mobile .item-setting").click(function(){
   $(".tabs-content-mobile").css("display","none");
   $(".tabs-setting").css("display","block");
  });
  
 });
 $(window).scroll(function () {
		if ($(this).scrollTop() > 350) {
			$('.hozmenu').addClass("fix-header");
			$('.hozmenu .nav-container').addClass("container");
			$('.header-content').addClass("fix-header");
			} else {
			$('.hozmenu').removeClass("fix-header");
			$('.hozmenu .nav-container').removeClass("container");
			$('.header-content').removeClass("fix-header");
		}
		
	});
});

</script>

